### ISSUE TITLE
Fallbacks?

### ISSUE THREAD

**Issue by Flamefire** [gpakosz/whereami#10]
How about a fallback or is this guaranteed to work always? E.g. https://stackoverflow.com/a/34109000/1930508 provides a solution which uses `argv[0]` and the current path as an (educated) guess if the other method fail.

**Comment by gpakosz** [comment]
`argv[0]` is not reliable.

The link you mentioned only addresses current executable path, not current module path.

**Comment by Flamefire** [comment]
True. I just liked the solution so use that as a fallback if the system call fails. It is not reliable, but a good guess for common circumstances.

**Comment by gpakosz** [comment]
I've been intrigued by people stating that in some situations current user doesn't have permissions to read `/proc` on Linux. This sounds really strange and never happened to me. I've been using this in production for around 10 years. As for currently unsupported operating systems, the fallback is too poor to be trusted.
