### ISSUE TITLE
OpenBSD support?

### ISSUE THREAD

**Issue by kpeeters** [gpakosz/whereami#13]
The current code for FreeBSD and friends does not work on OpenBSD (I've been told there's no more support for /kern and /proc on that platform). Any ideas on how to do this on OpenBSD?

**Comment by gpakosz** [comment]
Hello @kpeeters,

I'm sorry I don't know much about OpenBSD. Maybe you can ask around and see if there's a equivalent for `KERN_PROC_PATHNAME`?

**Comment by gpakosz** [comment]
Closing. It seems OpenBSD has privacy concerns that led to the decision of not allowing processes to discover where they are located on the disk 🤷‍♂️

**Comment by c64skin** [comment]
i know you have closed it but here's a implementation for openbsd that maybe is of interest:
https://github.com/ibara/getexecname

i'll try to mash it into your code either way, i need it for dosbox-x .

**Comment by gpakosz** [comment]
Hello @kpeeters and @frakswe 👋

Can you please try the `gh-13` branch?

**Comment by c64skin** [comment]
Well i just dropped it in the dosbox-x folder and it fired right up on the first try :)

That's as far as i've tested it though.

**Comment by gpakosz** [comment]
I tested
- unsetting `PATH`
- putting garbage in `PATH`

I don't know, without forcing it in the code, how to reproduce `argv[0]` not being the absolute path to the executable
