### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by bstaletic** [gpakosz/whereami#17]
Providing a `CMakeLists.txt instead of platform specific build files would improve a couple of things:

- Instead of one file per build system, it would only be necessary to maintain one `CMakeLists.txt`.
- It would cover support for some build systems not currently supported (`ninja` for example).
- Bazel recently gained support for consuming cmake files.

I haven't done any extensive testing, but I did write a simple `CMakeLists.txt` for `wip-cpp` branch:

```cmake
project( whereami )
cmake_minimum_required( VERSION 2.8 )

add_library( ${PROJECT_NAME} STATIC whereami.c whereami.h )
set_target_properties( ${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ON )
target_include_directories( ${PROJECT_NAME} SYSTEM PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} )

add_library( ${PROJECT_NAME}-cpp STATIC whereami++.cpp whereami++.h )
set_target_properties( ${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ON )
target_include_directories( ${PROJECT_NAME}-cpp SYSTEM PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} )
target_link_libraries( ${PROJECT_NAME}-cpp ${PROJECT_NAME} )
```

It is able to produce `libwhereami.a` and `libwhereami-cpp.a` and the simplest possible example worked as expected:
```c++
#include <iostream>
#include "../src/whereami++.h"
int main(void)
{
        std::cout << whereami::getExecutablePath();
        return 0;
}
```
Executable was compiled with `g++ -c foo.cpp -o foo.o` and linked with `g++ foo.o libwhereami++.a -o foo`.

Alternatively, providing pkgconfig files would also work with cmake.

**Comment by gpakosz** [comment]
Hello @bstaletic 👋

I'm not convinced by using CMake. I personally don't like it nor use it. As such, a `CMakeLists.txt` would be a liability.

And as far as `whereami` goes, it's a 2 files library **on purpose**. Just drop it in your own project and call it a day, whatever your build system of choice is.

In fact the examples in this repository have little value in their compiled form.

As far as the `wip-cpp` branch goes, I had many discussions with different senior C++ developers and the C++isms just seem to ["complect"](https://www.infoq.com/presentations/Simple-Made-Easy) things instead of bringing concrete value to the table.

**Comment by bstaletic** [comment]
First of all, thanks for the quick response.

> I'm not convinced by using CMake. I personally don't like it nor use it. As such, a CMakeLists.txt would be a liability.

That's an understandable point of view. I don't like either.

> And as far as whereami goes, it's a 2 files library on purpose. Just drop it in your own project and call it a day, whatever your build system of choice is.

That's exactly what I'm doing right now, at least locally. On the other hand, the license of whereami isn't lawyer-friendly. I've heard people say that company employed lawyers say something along the lines of "by choosing to say nothing, WTFPL has many unintended implications", in other words, WTFPL licensed libraries won't be in any corporate environment's toolbox of libraries.

> In fact the examples in this repository have little value in their compiled form.

I actually read the examples rather than the `README.md` to understand how am I supposed to use the library.

Finally, I'll close the issue since cmake support isn't going to happen.

**Comment by gpakosz** [comment]
Thanks for raising your concern about the license.

I just pushed a change to dual license it under both MIT and WTFPL v2.

Does it help?

**Comment by bstaletic** [comment]
As far as I know MIT is perfectly fine, though I am not a lawyer.

**Comment by PierceLBrooks** [comment]
https://github.com/PierceLBrooks/whereami-cmake/commit/7f0d707945a275d6d45a84113474159983bd0dfb
