### ISSUE TITLE
Interface for getting the directory and not the full path is cumbersome

### ISSUE THREAD

**Issue by jeremyong** [gpakosz/whereami#18]
First, thanks for providing this library to the community!

I would imagine that the use case of grabbing just the directory containing the executable and not the full path is fairly common.

Currently, doing so requires running the filesystem routines twice, and performing an allocation with more memory than necessary. None of this should be necessary given that the full path is available internally on the stack.

**Comment by gpakosz** [comment]
Hello @jeremyong 👋

> Currently, doing so requires running the filesystem routines twice, and performing an allocation with more memory than necessary.

Is allocating few more bytes for the executable name really a problem?

> None of this should be necessary given that the full path is available internally on the stack.

I don't believe this assertion is actually true. If you look at the `getModulePath_()` function used on Windows, sure there are two buffers on the stack, but ultimately `dirname_length` has to be computed in "UTF-8 space" after a client buffer large enough has been successfully filled by `WideCharToMultiByte()`.

My recommendation would be to first try calling `getExecutablePath()` with a buffer of `1024`, `2048` or `4096` bytes on caller's stack. And only if it's not enough resort to heap allocation, which imho is going to be really rare.
