### ISSUE TITLE
Unused variable 'count' in getModulePath

### ISSUE THREAD

**Issue by floooh** [gpakosz/whereami#2]
Just a tiny thing that I just noticed again when dropping the latest version into my project, there's an unused variable here:

https://github.com/gpakosz/whereami/blob/master/src/whereami.c#L234

Xcode gave me a warning and I removed it in my local copy, but may be better to fix it upstream :)

**Comment by gpakosz** [comment]
Ah yeah I spotted it in another copy :) Fixed!
