### ISSUE TITLE
#ifdef WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by mikejsavage** [gpakosz/whereami#21]
Would be nice to silence warnings like `whereami.cpp(51): warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition` :)

**Comment by gpakosz** [comment]
Hello @mikejsavage 

I see 2 situations where this could happen
• either you're defining `WIN32_LEAN_AND_MEAN` at the build level, e.g. with `CPPFLAGS=-DWIN32_LEAN_AND_MEAN`
• or you're including `whereami.c` in another compilation unit that already defines `WIN32_LEAN_AND_MEAN`

Are you doing one of the two?

In any case, can you please try the `gh-21` branch?

**Comment by gpakosz** [comment]
Wait a minute `whereami.cpp`? 🤔

**Comment by mikejsavage** [comment]
I was defining WIN32_LEAN_AND_MAN at the build level yes, and gh-21 fixes it

> whereami.cpp

Easier to rename it than add a C rule to the build system 🤦‍♂️
