### ISSUE TITLE
Precompile header

### ISSUE THREAD

**Issue by mjako78** [gpakosz/whereami#22]
Hello, I'm trying to using your library in a project, using an older version of Visual Studio 2003
(I'm stuck with this version to maintaining a legacy app which needs the compiler and linker shipped with that VS version - sad story 😭 ).

If I set "use precompiled header" in project properties, I have this error on building
`whereami.c(680): fatal error C1010: unexpected end of file while looking for precompiled header directive`.

If I don't use precompiled header in project properties, I have this error
`whereami.c(56): fatal error C1083: Cannot open include file: 'intrin.h': No such file or directory`
This header is not present on Windows installation (I searched entire C drive)

What can I do to use your library with precompiled header?

**Comment by gpakosz** [comment]
Hello @mjako78 👋

The error has nothing to do with the use of precompiled headers.

It seems Visual Studio 2003 doesn't come with the `intrin.h` header.
Looking at the code, I guess you can just remove the `#include <intrin.h>` line in `whereami.c`.

I'll do a proper analysis later on to find out why it was once needed.

**Comment by gpakosz** [comment]
On and if you really need to use precompiled headers you have to modify `whereami.c` anyways to include the precompiled header. But that's ok imho as `whereami.h` and `whereami.c` are supposed to be dropped in your own codebase.

**Comment by mjako78** [comment]
Thank for your quick answer.
I tried to remove the `#include <intrin.h>` line in `whereami.c`, but with no luck; I now have different errors:
```
whereami.c(150) : warning C4013: 'GetModuleHandleEx' undefined; assuming extern returning int
whereami.c(150) : error C2065: 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS' : undeclared identifier
whereami.c(150) : error C2065: 'GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT' : undeclared identifier
```
After some research seems that `intrin.h` was shipped with VS 2005 onwards.

If I try to add an include for precompiled header directly in `whereami.c` I have the following error:
`whereami.c(13): fatal error C1853: 'Release/CurrentDirTrigger.pch' precompiled header file is from a previous version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)`

**Comment by gpakosz** [comment]
That's weird.

`GetModuleHandleEx` comes with `#include <windows.h>`, see https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandleexa

The `intrin.h` header indeed ships with Visual Studio 2005 and onwards but `whereami.c` doesn't make use of any intrinsic defined in this header.

About precompiled headers, you can rename `whereami.c` to `whereami.cpp` in your project.

**Comment by mjako78** [comment]
Really weird.
I renamed `whereami.c` to `whereami.cpp`, but I go back to
 `fatal error C1083: Cannot open include file: 'intrin.h': No such file or directory`, 
and if I remove that include from source file, the compiler complains about undefined method `GetModuleHandleEx`.

I am trying to search internet for a copy of VS 2005 to get `intrin.h` header as last chance 😢

**Comment by gpakosz** [comment]
Well I suspect you'll get past the include error but `GetModuleHandleEx` won't be defined as well 🤷‍♂️

The [MSDN page](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandleexa) says
> To compile an application that uses this function, define _WIN32_WINNT as 0x0501 or later. For more information, see Using the [Windows Headers](https://docs.microsoft.com/en-us/windows/desktop/WinProg/using-the-windows-headers).

**Comment by gpakosz** [comment]
Hey @mjako78 👋

Did you sort it out?
