### ISSUE TITLE
Visual Studio giving error of "GetModuleFilenameW undefined"?

### ISSUE THREAD

**Issue by Jimw338** [gpakosz/whereami#25]
<warning: annoyed tone> Not sure anyway can help with this - any ideas why Visual Studio would say that GetModuleFilenameW would be undefined?  I'm running V-Studio 2019 on Windows 10, inside Parallels Pro on a Mac. The project is a "default" "Console C++" project, and the source files (somehow) compiled the last time I compiled it a couple months ago.  Since then, I reinstalled the Parallels app with a new license, but (as far as I can tell) am using the same virtual machine (the same pvm file).

I have no idea what the "version" of V-Studio is.  Or *where* it is - at least xCode has an "About" menu item - did that little interface nicety somehow escape MS's UX team?

("Wait - *WHAT* UX team?  Oh, they must have been the victim of the Mexican Standoff in the infamous Microsoft Org Chart")

**Comment by gpakosz** [comment]
Hello @Jimw338 👋

I don't know. [`GetModuleFileNameW`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew) is definitely available in Visual Studio 2019.
