### ISSUE TITLE
Adding some CMake example?

### ISSUE THREAD

**Issue by melroy89** [gpakosz/whereami#28]
Hi,

This is an easy CMake example of adding `whereami` to an existing CMake project as static library, third party libraries can be extended with CMake config files if you want.

Anyway, this would be the CMakeLists.txt file where you place both the .c & .h next to each other. So the structure would be:

- whereami.h
- whereami.c
- CMakeLists.txt 

```cmake
project(whereami)

set(TARGET_NAME ${PROJECT_NAME})

# Create static library
add_library(${TARGET_NAME} STATIC whereami.c)

# Use PUBLIC iso INTERFACE, so the library itself also finds it's own header file
target_include_directories(
    ${TARGET_NAME}
    PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}
)
```

But for now, this works for me.

**USAGE:**

```cmake
target_link_libraries(your_target PRIVATE whereami)
```

Of course if you have sub-folders where you got a dedicated CMakeLists.txt in your `/src` folder. Don't forget the add the sub directory to your root CMakeLists.txt file, example (assuming the whereami project is located in `lib/whereami` folder structure):

```cmake
add_subdirectory (lib/whereami)
add_subdirectory (src)
```

It's that easy, it will automatically find the  header file..

**Comment by gpakosz** [comment]
Hello @danger89 👋

There's no point compiling Where Am I? as a library itself.

Those using CMake just have to add the sources to their `CMakeLists.txt` file.

**Comment by melroy89** [comment]
Static library I was talking about, not a real separate library. Do **NOT** think in terms of `.dll` or `.so`. but just simple .a file. 
Which is a great way of reusing the code, without the need for recompiling in different projects. Or within your own project for that matter.

**Comment by PierceLBrooks** [comment]
https://github.com/PierceLBrooks/whereami-cmake/commit/7f0d707945a275d6d45a84113474159983bd0dfb

**Comment by melroy89** [comment]
> [PierceLBrooks@7f0d707](https://github.com/PierceLBrooks/whereami-cmake/commit/7f0d707945a275d6d45a84113474159983bd0dfb)

Great!
