### ISSUE TITLE
Build fails on macOS when not defining _DARWIN_C_SOURCE

### ISSUE THREAD

**Issue by melroy89** [gpakosz/whereami#34]
Sorry to both you [again](https://github.com/gpakosz/whereami/issues/33). While the `realpath` issue is solved. 

I'm trying to [build](https://github.com/LibreWeb/Browser/runs/5073730731?check_suite_focus=true) my project which includes _whereami_ towards **MacOS** platform now.

Resulting into the following errors now:

```log
 /Users/runner/work/Browser/Browser/lib/whereami/whereami.c:431:5: error: use of undeclared identifier 'Dl_info'
    Dl_info info;
    ^
/Users/runner/work/Browser/Browser/lib/whereami/whereami.c:433:9: error: implicit declaration of function 'dladdr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (dladdr(WAI_RETURN_ADDRESS(), &info))
```

I tried to raise the `_XOPEN_SOURCE` from 500 to even 700, without luck (`target_compile_definitions(${LIBARY_NAME} PUBLIC _XOPEN_SOURCE=700)`). I try to enable C extensions. Also without any luck...

Do you have missing includes in the MacOS ifdef section? I'm the cmake build system for my code. Both native Linux & Windows cross-compile builds are working.

I'm out of ideas. Thanks in advance!

Regards,
Melroy van den Berg

**Comment by gpakosz** [comment]
Hello @danger89,

You n`-D_DARWIN_C_SOURCE`, please refer to `_gnu-make/Makefile`.

**Comment by melroy89** [comment]
OK let me try that. 

Why not add it to the source code? 

![Screenshot_20220205-041905_ProtonMail](https://user-images.githubusercontent.com/628926/152636334-e0b4ce06-c297-4173-9565-95ce17a7bcf7.png)

**Comment by gpakosz** [comment]
Adding it to the source code is more fragile than adding it to the build system and it complicates the myriad of `#ifndef` logic that's already existing

**Comment by melroy89** [comment]
Owh oke. Well maybe you want to add `_DARWIN_C_SOURCE` note clearly in the README.md together with the `_XOPEN_SOURCE`

**Comment by gpakosz** [comment]
Can you please try the `gh-33-34` branch and confirm it builds without defining `_DARWIN_C_SOURCE` from CMake?

**Comment by melroy89** [comment]
Sure, I will try this soon. What changed your mind?

**Comment by gpakosz** [comment]
At first I didn't want to complicate the preprocessor logic. Preprocessor symbols like `_XOPEN_SOURCE` or `_DARWIN_C_SOURCE` have to be defined before including the first header and `whereami.c` includes `<stdlib.h>` early to  bring `malloc()` and `free()` in.

**Comment by melroy89** [comment]
So instead of `_BSD_SOURCE` that should be:

```cpp
#undef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
```

As stated here: https://github.com/gpakosz/whereami/issues/33#issuecomment-1040943407

The MacOS Build seems to work fine with your `_DARWIN_C_SOURCE` & `_DARWIN_BETTER_REALPATH` defines.
