### ISSUE TITLE
Adding an option or function to return an allocated string

### ISSUE THREAD

**Issue by darealshinji** [gpakosz/whereami#36]
The main idea behind this is that on several systems `realpath()` is used which returns an allocated string. But when I I create a buffer with malloc() and pass is to a wai_* function I could instead just received the original allocated string?

**Comment by gpakosz** [comment]
Hello @darealshinji 👋

That would change the API for no good reason imho.
It's not as if you would call `wai_getExecutablePath()` or `wai_getModulePath()` in a loop so the extra allocation is best left as an implementation detail when `realpath()` is being used.
