### ISSUE TITLE
FreeBSD not supported

### ISSUE THREAD

**Issue by dafixa** [gpakosz/whereami#4]
Please consider adding FreeBSD support.

Something like:

```
#include <sys/types.h>
#include <sys/sysctl.h>
#include <string.h>

WAI_FUNCSPEC
int WAI_PREFIX(getExecutablePath)(char* out, int capacity, int* dirname_length)
{
    char exePath[2048];
    int mib[4];  mib[0] = CTL_KERN;  mib[1] = KERN_PROC;  mib[2] = KERN_PROC_PATHNAME;  mib[3] = -1;
    size_t len = sizeof(exePath)-1;
    *exePath = '\0';
    if (sysctl(mib, 4, exePath, &len, NULL, 0) != 0)
        exePath[0] = '\0';
    else
        exePath[sizeof(exePath)-1] = '\0';

    char* resolved = exePath;

    int length = (int)strlen(resolved);
    if (length <= capacity)
    {
      memcpy(out, resolved, length);

      if (dirname_length)
      {
        int i;

        for (i = length - 1; i >= 0; --i)
        {
          if (out[i] == '/')
          {
            *dirname_length = i;
            break;
          }
        }
      }
    }

    return length;
}

```

**Comment by gpakosz** [comment]
Can you please have a look at the `freebsd` branch and tell me whether it works for you?

**Comment by gpakosz** [comment]
@dafixa Man did you just vanish after having requested a feature?

**Comment by dafixa** [comment]
> Man did you just vanish after having requested a feature?

Yes, and now I'm back.

@gpakosz The freebsd branch looks good. Thanks! 

One thing: The preprocessor guard is **FreeBSD** in the branch. I wonder if this works for NetBSD and OpenBSD as well, but I have no experience with these and no time to test.

**Comment by dafixa** [comment]
Also, will the freebsd branch be merged into master anytime soon?

**Comment by gpakosz** [comment]
Hi!

I'm glad you're back. I have no idea yet about NetBSD and OpenBSD. I think for NetBSD one has to read the `/proc/curproc/exe` symlink. I'll figure that out later.
