### ISSUE TITLE
getModulePath and paths with spaces

### ISSUE THREAD

**Issue by starseeker** [gpakosz/whereami#40]
Hi!  I've hit a case where the sscanf used to parse the WAI_PROC_SELF_MAPS lines at whereami.c:361 winds up not getting a path that contains a  space in the name (it comes from one of our test paths in our main build).  Here's what shows in gdb:

```
(gdb) print (const char *)buffer
$1 = 0x7fffffff8870 "7ffff4c6c000-7ffff4d44000 r-xp 0006c000 103:03 4500978", ' ' <repeats 19 times>, "/home/user/brlcad/build/distcheck-odd_pathnames/1 Odd_ build dir ++/lib/libbu.so.20.0.1\n"
(gdb) print (const char *)path
$2 = 0x7fffffff9870 "/home/user/brlcad/build/distcheck-odd_pathnames/1"
```

Would it be possible to adjust this logic so the full path is returned in such cases?

**Comment by starseeker** [comment]
In case it's helpful, the following (based on the hint from https://stackoverflow.com/a/50440783/2037687) seemed to work for my test case in our local copy (not sure this is how you'd want to fix it, but adding it for reference:

```
--- whereami.c.orig	2024-05-10 12:54:09.409689412 -0400
+++ whereami.c	2024-05-10 12:56:15.043581917 -0400
@@ -271,18 +271,21 @@
       uint32_t major, minor;
       char path[PATH_MAX];
       uint32_t inode;
+      int poffset = -1;
 
       if (!fgets(buffer, sizeof(buffer), maps))
         break;
 
-      if (sscanf(buffer, "%" PRIx64 "-%" PRIx64 " %s %" PRIx64 " %x:%x %u %s\n", &low, &high, perms, &offset, &major, &minor, &inode, path) == 8)
+      if (sscanf(buffer, "%" PRIx64 "-%" PRIx64 " %s %" PRIx64 " %x:%x %u %n\n", &low, &high, perms, &offset, &major, &minor, &inode, &poffset) == 7)
       {
         uint64_t addr = (uintptr_t)WAI_RETURN_ADDRESS();
-        if (low <= addr && addr <= high)
+        if (low <= addr && addr <= high && poffset > 0)
         {
           char* resolved;
+	  char *opath = buffer+poffset;
+	  opath[strlen(opath)-1] = '\0';
 
-          resolved = realpath(path, buffer);
+          resolved = realpath(path, opath);
           if (!resolved)
             break;

```

**Comment by gpakosz** [comment]
Hello @starseeker 👋

Thanks for the report!
Can you please try the `gh-40` branch?

**Comment by starseeker** [comment]
It needs a compile fix (the endif) but it does appear to work.

**Comment by starseeker** [comment]
(I also needed to do the following to get the compiler to accept line 285:)

```
void *paddr = WAI_RETURN_ADDRESS();
uint64_t addr = (uint64_t)(uintptr_t)paddr;
```

**Comment by gpakosz** [comment]
You have to add a cast also when compiling the `master` branch, right?

Can you share the exact error message?

**Comment by starseeker** [comment]
Sure:
```
whereami.c:285:25: error: cast from function call of type ‘void *’ to non-matching type ‘long unsigned int’ [-Werror=bad-function-cast]
  285 |         uint64_t addr = (uintptr_t)WAI_RETURN_ADDRESS();
      |                         ^

```

**Comment by starseeker** [comment]
And yes, that's an issue with master branch as well.

**Comment by gpakosz** [comment]
Thanks, can you open a dedicated issue for that please?

I'll close the `/proc/self/maps` parsing by merging the `gh-40` branch

**Comment by gpakosz** [comment]
Can you please confirm what I force pushed in `gh-40` still works for you modulo `-Wbad-function-cast`?

**Comment by starseeker** [comment]
Looks like it does, yes.
