### ISSUE TITLE
Werror=bad-function-cast compile issue

### ISSUE THREAD

**Issue by starseeker** [gpakosz/whereami#41]
Getting the following compilation error:

```
whereami.c:285:25: error: cast from function call of type ‘void *’ to non-matching type ‘long unsigned int’ [-Werror=bad-function-cast]
  285 |         uint64_t addr = (uintptr_t)WAI_RETURN_ADDRESS();
      |                         ^
```

In our local copy, we do the following:

```
void *paddr = WAI_RETURN_ADDRESS();
uint64_t addr = (uint64_t)(uintptr_t)paddr;
```

**Comment by gpakosz** [comment]
Hello @starseeker 👋

Thanks for the report!
The `-Wbad-function-cast` warning is not enabled by `-Wall` nor `-pedantic`, so I added it and changed the code.

Can you please try the `gh-41` branch?

**Comment by starseeker** [comment]
Looks like that works.
