### ISSUE TITLE
Unable to get dirname_length when capacity is less than executable path's length

### ISSUE THREAD

**Issue by RolandMarchand** [gpakosz/whereami#43]
# Problem

In the function `wai_getExecutablePath()`, when the argument `capacity` is less than the return value (the length of the executable path), `dirname_length` is not written to, even when the command was run successfully and the executable path's length is found.

# Versions

- whereami: f5e3eac441acbb4ec1fe3e2c32646248ae463398
- GCC: `gcc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1)`
- OS: `GNU/Linux fedora 6.10.4-200.fc40.x86_64, Fedora Linux 40 (Workstation Edition)`

# Example

```c
#include <limits.h>
#include <stdio.h>
#include "whereami.h"

int main() {
	char buffer[PATH_MAX];
	int execDirLength;
	int execPathLength = wai_getExecutablePath(NULL, 0, &execDirLength);

	wai_getExecutablePath(buffer, execPathLength - 1, &execDirLength);
	
	// <execPathLength>, 0
	printf("path: %d, dir: %d\n", execPathLength, execDirLength);

	wai_getExecutablePath(buffer, execPathLength, &execDirLength);

	// <execPathLength>, <execDirLength>
	printf("path: %d, dir: %d\n", execPathLength, execDirLength);

	// <execPathLength>, <execDirLength>
	printf("path: %d, dir: %d\n", execPathLength + 1, execDirLength);
}
```

**Comment by gpakosz** [comment]
Hello @RolandMarchand,

If there's enough capacity, there's no way to retrieve the path and as such there's no way to know where the last `/` character is.

**Comment by lazzy-cipher** [comment]
> Hello @RolandMarchand,
> 
> If there's enough capacity, there's no way to retrieve the path and as such there's no way to know where the last `/` character is.

I see. I was originally mislead by the example that showcased my desired behavior, and the limitation wasn't mentioned in the header.
https://github.com/gpakosz/whereami/blob/f5e3eac441acbb4ec1fe3e2c32646248ae463398/example/executable.c#L75
