### ISSUE TITLE
Windows version of wai_getExecutablePath() returns length one past end of string

### ISSUE THREAD

**Issue by floooh** [gpakosz/whereami#5]
Hi, @kaffeewolf found a bug in the Windows implementation of wai_getExecutablePath(). It's also caught by the unit test I wrote in Oryol, but embarassingly I never ran this on Windows :)

Here it goes: the length returned by wai_getExecutablePath() is different between Windows and non-Windows platforms. On non-Windows-platforms, the length of the path string is returned (in number of bytes), which I think is the intended behaviour. On Windows however, the returned length is one bigger.

The reason is that the length on Windows is taken from the return value of WideCharToMultiByte() (https://github.com/gpakosz/whereami/blob/master/src/whereami.c#L99), and WideCharToMultiByte() returns the _number of bytes written to the output buffer_ (https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130(v=vs.85).aspx), and this includes the terminating zero, and this means, wai_getExecutablePath() (or rather already wai_getModulePath()) returns the length _including_ the terminating 0, which is different from the other platforms.

Link to Oryol ticket: https://github.com/floooh/oryol/issues/220

**Comment by gpakosz** [comment]
Thanks for the report!

**Comment by floooh** [comment]
Confirmed working, tanks for the quick fix :)
