### ISSUE TITLE
Returned path length is off by one

### ISSUE THREAD

**Issue by DanielSWolf** [gpakosz/whereami#6]
According to documentation, the path length returned by `wai_getExecutablePath` is the actual number of characters _without_ a terminating zero byte. Actually, at least on Windows, the value returned _includes_ the trailing zero byte.

This can lead to bugs. For instance, when creating a string like this:

```
std::string path(buffer, length);
```

The result is a string with length `length` that (wrongly) contains a zero character _as part of the string_.

I see two possible solutions. If _all_ platforms consistently add the zero byte, just the documentation needs to be changed. Otherwise, the individual implementations should be changed to behave consistently.

**Comment by gpakosz** [comment]
I believe that's addressed by ba75d51713a5a0eb8e617a28dcff4998f96b85e2 that fixes #5?

**Comment by DanielSWolf** [comment]
Consider this a duplicate.

**Comment by gpakosz** [comment]
Sorry for the inconvenience
