### ISSUE TITLE
#error unsupported platform

### ISSUE THREAD

**Issue by ghost** [gpakosz/whereami#8]
I attempted to build a slightly modified version of WhereAmI.c and WhereAmI.h in Eclipse Neon as both C and a C++ project. In both instances of the project it failed to build with the following errors.
{
**** Incremental Build of configuration Debug for project WhereAmI ****
make all 
Building file: ../src/WhereAmI.cpp
Invoking: Cygwin C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/WhereAmI.d" -MT"src/WhereAmI.o" -o "src/WhereAmI.o" "../src/WhereAmI.cpp"
../src/WhereAmI.cpp:661:2: error: #error unsupported platform
 #error unsupported platform
  ^
make: *** [src/subdir.mk:20: src/WhereAmI.o] Error 1

Build Finished (took 277ms)
}
The only modification I made was in WhereAmI.c at line 11.
{
#if !defined(WHEREAMI_H)
#include "WhereAmI.h"
// Changed from <WhereAmI.h> to "WhereAmI.h" to reference it locally.
#endif
}

**Comment by gpakosz** [comment]
Can you please try the `cygwin` branch?

**Comment by ghost** [comment]
The new Cygwin branch fixed my issue. Sorry for the late response.

**Comment by gpakosz** [comment]
Alright, I merged the branch. Thanks for the report!
